# ============== Application configuration ==================== #
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: katohdavid@gmail.com
    password: fxzyuynzfnfvqoqo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# ============== Eureka Discovery configuration ==================== #
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9293/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
