# ============== Application configuration ==================== #
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: katohdavid@gmail.com
    password: fxzyuynzfnfvqoqo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# ============== Eureka Discovery configuration ==================== #
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9093/eureka/

env: Dev Environment. All configuration here are meant for development.
