spring:
  datasource: # Database configuration #
    url: jdbc:mysql://localhost:3306/files_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 38NG/db@tro38
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

app:
  file:
    storage-root: ${user.home}/FileStorage
    max-file-size: 100MB
    allowed-content-types:
      - application/pdf
      - application/vnd.openxmlformats-officedocument.wordprocessingml.document
      - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      - video/mp4
      - video/x-msvideo # Microsoft video (.avi)
      - video/x-quicktime # Apple video (.mov)
