spring:
  cloud:
    gateway:
      routes:
        - id: otp
          uri: lb://otp
          predicates:
            - Path=/otp/**
        - id: email
          uri: lb://email
          predicates:
            - Path=/email/**
        - id: file
          uri: lb://file
          predicates:
            - Path=/files/**

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9293/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
