# ============== Application configuration ==================== #
spring:
  datasource: # Database configuration #
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/otp_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_ROOT_USER}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# ============== Eureka Discovery configuration ==================== #
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:9293/eureka}
  instance:
    prefer-ip-address: true

# ============== Metrics Exposition ====================
management:
  endpoints:
    web:
      exposure:
        include: ["prometheus"]

# ============== OTP configurations ====================
otp:
  length: 6
  charset: "0123456789"
  expiry-min: 10
  max-attempts: 5
